// <auto-generated />
using System;
using JiraProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiraProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("JiraProject.Models.KyThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiKyThi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhongThi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KyThis");
                });
#pragma warning restore 612, 618
        }
    }
}
